### ISSUE TITLE
How to Build the Project in a Windows Environment

### ISSUE THREAD

**Issue by wonengkanjiannideyanjing** [lanl/truchas-pbf#1]
I want to build the project on my local Windows environment, but I encountered some issues. CMake is indicating that it cannot find the Fortran compiler. How can I resolve this?My computer has an AMD CPU, but I provided the path to the Intel Fortran compiler. I'm not sure if this will cause any issues.
![微信图片_20241120212920](https://github.com/user-attachments/assets/92a5a6eb-ca96-44c2-b95f-25736b827a6c)

**Comment by nncarlson** [comment]
Hi @wonengkanjiannideyanjing.  It's fine to use the Intel compilers with an AMD CPU, but we don't support building on Windows, only Linux.  Although we don't do it ourselves (we're not Windows users), it should be possible to build inside the WSL (Windows Subsystem for Linux).

Note that this github project is just a stub to redirect to the actual project at https://gitlab.com/truchas-pbf/truchas-pbf.  So I'm going to close this issue.  You're welcome to open an issue there, but you'll need to provide full information in order for us to help: the steps you've taken and the command lines and the full output of the commands.
